pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    // environment { 
    //     MyENV = 'Hello Jenkins '
    // }
    parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    options {
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('init') {
            steps {
                sh '''
                    cd 01-vpc/
                    terraform init -reconfigure
                '''
            }
        }
        stage('plan') {
            steps {
                sh '''
                    cd 01-vpc/
                    terraform plan
                '''
            }
        }
        stage('apply') {
            when {
                expression { params.action == "apply"}
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh '''
                    cd 01-vpc/
                    terraform apply -auto-approve
                '''
            }
        }
        stage('destroy') {
            when {
                expression { params.action == 'destroy'}
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh '''
                    cd 01-vpc/
                    terraform destroy -auto-approve
                '''
            }
        }
        // stage('destroy') {
        //     steps {
        //         sh '''
        //             cd 01-vpc/
        //             terraform destroy -auto-approve
        //         '''
        //     }
        // }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success {
            echo 'I will say Hello when success!'
        }
        failure {
            echo 'I will say Hello when failure!'
        }
    }
}