pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    // environment { 
    //     MyENV = 'Hello Jenkins '
    // }
    options {
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds()
    }
    stages {
        stage('init') {
            steps {
                terraform init -reconfigure
            }
        }
        stage('plan') {
            steps {
                terraform plan
            }
        }
        stage('apply') {
            steps {
                terraform apply -auto-approve
            }
        }
        stage('destroy') {
            steps {
                terraform destroy -auto-approve
            }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success {
            echo 'I will say Hello when success!'
        }
        failure {
            echo 'I will say Hello when failure!'
        }
    }
}